---
name: Checks

# it'll run on every push
on: [push]

# define automated jobs here
jobs:
  # for testing and linting
  test-lint:
    name: Test and Lint
    # use os for run your app
    runs-on: ubuntu-20.04
    # define no of steps to create testing and linting
    steps:
        # login to your docker hub account
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          #  it'll get dockerhub user and password from repo secrets, defined via repo settings
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        #  this step will check code is exists for not
      - name: Checkout
        uses: actions/checkout@v2
        # it'll run testing
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
        # it'll run linting using flake8
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"